export const imgData = [
  {
    id: 1,
    category: "graphic",
    urlName: "ctbc_ecash",
    name: "中信ecash",
    portfolioCover: require("../img/portfolio/dm_ctbc_ecash.png"),
    workCover: require("../img/work/ctbc_ecash/ctbc_ecash.png"),
    gallery: [
      "./img/work/ctbc_ecash/000.jpg",
      "./img/work/ctbc_ecash/ctbc_ecash.png",
    ],
    liveDemo: "",
  },
  {
    id: 2,
    category: "website",
    urlName: "mli_lunar",
    name: "三商美邦中秋賀卡",
    portfolioCover: require("../img/work/mli_lunar/mli_lunar_workcover.jpg"),
    workCover: require("../img/work/mli_lunar/mli_lunar_workcover.jpg"),
    gallery: [
      "./img/work/mli_lunar/mli_lunar1.jpg",
      "./img/work/mli_lunar/mli_lunar2.jpg",
      "./img/work/mli_lunar/mli_lunar3.jpg",
    ],
    liveDemo: "https://richad.com.tw/test/230913-mli-moon_fest/",
  },
  {
    id: 3,
    category: "graphic",
    urlName: "ctbc_birthday",
    name: "中信生日卡",
    portfolioCover: require("../img/work/ctbc_birthday/ctbc_birthday3.jpg"),
    workCover: require("../img/work/ctbc_birthday/ctbc_birthday3.jpg"),
    gallery: [
      "./img/work/ctbc_birthday/ctbc_birthday1.jpg",
      "./img/work/ctbc_birthday/ctbc_birthday2.jpg",
      "./img/work/ctbc_birthday/ctbc_birthday3.jpg",
      "./img/work/ctbc_birthday/ctbc_birthday4.jpg",
    ],
    liveDemo: "",
  },
  {
    id: 4,
    category: "graphic",
    urlName: "landbank_recruit",
    name: "土地銀行新進人員招募DM",
    portfolioCover: require("../img/work/landbank_recruit/landbank_recruit1.jpg"),
    workCover: require("../img/work/landbank_recruit/landbank_recruit1.jpg"),
    gallery: [
      "./img/work/landbank_recruit/landbank_recruit1.jpg",
      "./img/work/landbank_recruit/landbank_recruit2.jpg",
    ],
    liveDemo: "",
  },
  {
    id: 5,
    category: "website",
    urlName: "taishin_exchange",
    name: "台新銀行 換匯活動",
    portfolioCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    workCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    gallery: [
      "./img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange2.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange3.jpg",
    ],
    liveDemo: "",
  },
  {
    id: 6,
    category: "website",
    urlName: "taishin_exchange",
    name: "台新銀行 換匯活動",
    portfolioCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    workCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    gallery: [
      "./img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange2.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange3.jpg",
    ],
    liveDemo: "",
  },
  {
    id: 7,
    category: "website",
    urlName: "taishin_exchange",
    name: "台新銀行 換匯活動",
    portfolioCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    workCover: require("../img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg"),
    gallery: [
      "./img/work/taishin_summer_exchange/taishin_summer_exchange1.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange2.jpg",
      "./img/work/taishin_summer_exchange/taishin_summer_exchange3.jpg",
    ],
    liveDemo: "",
  },
];
